/*
Group Number: 28
1. Anishka Singh 2020B3A70816P
2. Gautam Jajoo 2020B3A71638P
3. Suraj Phalod 2020B3A71959P
4. Ria Shekhawat 2020B4A71986P
5. Karan Agrawal 2020B4A70830P
*/
#include "whole_include.h"
#include <time.h>

void lexical_analysis(char *input_filename)
{
    // info("Performing Lexical Analysis");
    Lexer lexer = init_lexer(input_filename);

    Token tk = getNextToken(lexer);

    Vector vec = init_vector(TOKEN);

    while ((lexer->fp))
    {
        push_back(vec, tk);
        tk = getNextToken(lexer);
    }

    for (int i = 0; i < vec->size; i++)
    {
        printf("Line no. %3ld  ", ((Token)get(vec, i))->line_num);
        if (((Token)get(vec, i))->type == 57)
        {
            printf("Error: %s", ((Token)get(vec, i))->error_msg);
        }
        else
        {
            printf("Lexeme %25s   ", (char *)(((Token)get(vec, i))->lexeme_str)->text);
            printf("Token %s", token_type_list[((Token)get(vec, i))->type]);
        }

        printf("\n");
    }

    info("Only Lexical analyzer module developed");
}

// Function to measure execution time
void measure_execution_time(char *filename)
{
    clock_t start_time, end_time;

    double total_CPU_time, total_CPU_time_in_seconds;

    start_time = clock();

    TreeNode tree = parseInputSourceCode(filename);

    end_time = clock();

    total_CPU_time = (double)(end_time - start_time);

    total_CPU_time_in_seconds = total_CPU_time / CLOCKS_PER_SEC;

    printf("\ntotal CPU time : %f", total_CPU_time);
    printf("\ntotal CPU time in seconds : %f", total_CPU_time_in_seconds);
}

// driver function to allow users to perform an execution of their choice
void driver(char *filename)
{
    int option;
    // char filename[100];
    do
    {
        printf("\n Options: \n");
        printf("0: For Exit\n");
        printf("1: For Removal of comments\n");
        printf("2: For printing the token list generated by the lexer \n");
        printf("3: For parsing and print parse tree \n");
        printf("4: For measuring the execution time \n");
        printf("Enter your choice: ");
        scanf("%d", &option);

        switch (option)
        {
        case 0:
            info("Exiting \n");
            exit(1);
            break;
        case 1:
            // printf(" Please enter the input file name (relative path): ");
            // scanf(" %[^\n]%*c", filename);
            // gets(filename);
            remove_comments(filename, "Test_Cases/comment_free_output.txt");
            info("The comment free code has been saved in location: Test_Cases/comment_free_output.txt");
            break;

        case 2:
            // printf(" Please enter the input file name (relative path): ");
            // scanf(" %[^\n]%*c", filename);
            lexical_analysis(filename);
            break;
        case 3:
            // printf(" Please enter the input file name (relative path): ");
            // scanf(" %[^\n]%*c", filename);
            parseInputSourceCode(filename);
            info("Both lexical and syntax analysis modules implemented");
            break;
        case 4:
            // printf(" Please enter the input file name (relative path): ");
            // scanf(" %[^\n]%*c", filename);
            measure_execution_time(filename);
            break;
        default:
            printf("Invalid option. Please try again.\n");
        }
    } while (option != 0);
}